### ISSUE TITLE
offchain compile-local command triggered DSP-related errors

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-api#36]
I have attempted to develop a zkgraph that includes offchain data source.
zkgraph.yaml as below:
```
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_event
description: "This demo zkGraph shows 3 ways to access / filter out source events."
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: mainnet
    event:
      - address: '0xa60ecf32309539dd84f27a9563754dca818b815e'
        events: 
          - "Sync(uint112,uint112)"
  - kind: offchain
    type: bytes

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```

mapping.ts as below:
```
export function handleBlocks(_: Block[], _: Bytes): Bytes {
  return Bytes.fromI32(1);
}
```

When I try to compile locally, I encounter this error with the command "compile-local".

```
> zkgraph compile --local

/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-api/dist/index.cjs:1929
      throw new Error(`Data Source Plugin Hub Key "${key}" doesn't exist.`);
            ^

Error: Data Source Plugin Hub Key "ethereum-offchain.bytes:local" doesn't exist.
    at DSPHub.getDSP (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-api/dist/index.cjs:1929:13)
    at DSPHub.getDSPByYaml (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-api/dist/index.cjs:1936:17)
    at compileLocal (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-cli/dist/index.cjs:382:40)
    at compile (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-cli/dist/index.cjs:365:30)
    at CAC.<anonymous> (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-cli/dist/index.cjs:922:7)
    at CAC.runMatchedCommand (/Users/xxx/Documents/xxx/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/Users/xxx/Documents/xxx/node_modules/cac/dist/index.js:541:12)
    at run (/Users/xxx/Documents/xxx/node_modules/@hyperoracle/zkgraph-cli/dist/index.cjs:1024:9)

Node.js v20.9.0
```

### version
zkgraph-lib: ^0.0.9-alpha.5
zkgraph-cli: 0.0.2-alpha.3
zkgraph-api: 0.1.9-alpha.6
